a = input("enter your first value : ")
b = input("enter your second value : ")
print("the sum of two numbers is :", int(a) + int(b))
print("the difference of two numbers is :", int(a) - int(b))
print("the product of two numbers is :", int(a) * int(b))
print("the quotient of two numbers is :", int(a) / int(b))
#relational operations
a = input("enter your first value :")
b = input("enter your second value :")
print("lets check :", int(a) == int(b))
print("lets check :" , int(a) != int(b))
print("lets check :" , int(a) > int(b))
print("lets check :" , int(a) < int(b))
print("lets check :" , int(a) >= int(b))
print("lets check :" , int(a) <= int(b))